Mon Aug 01 17:44:29 EET 2022 : Apache Derby Network Server - 10.11.1.2 - (1629631) started and ready to accept connections on port 1527
----------------------------------------------------------------
Mon Aug 01 17:44:29 EET 2022:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance a816c00e-0182-5a14-7f3b-000056395d73 
on database directory G:\material kolya\level 3\summer\software engineering\project\Bug-Tracking-System\Bug Tracker System with class loader sun.misc.Launcher$AppClassLoader@266474c2 
Loaded from file:/C:/Program%20Files/Java/jdk1.8.0_162/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_162-b12
user.dir=C:\Program Files\Java\jdk1.8.0_162\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=G:\material kolya\level 3\summer\software engineering\project\Bug-Tracking-System
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Mon Aug 01 17:44:34 EET 2022:
Shutting down instance a816c00e-0182-5a14-7f3b-000056395d73 on database directory G:\material kolya\level 3\summer\software engineering\project\Bug-Tracking-System\Bug Tracker System with class loader sun.misc.Launcher$AppClassLoader@266474c2 
Mon Aug 01 17:44:34 EET 2022 Thread[DRDAConnThread_2,5,main] (DATABASE = Bug Tracker System), (DRDAID = {2}), Database 'Bug Tracker System' shutdown.
Mon Aug 01 17:44:46 EET 2022 Thread[DRDAConnThread_2,5,main] Cleanup action starting
java.sql.SQLException: Database 'Bug Tracker' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR XJ004: Database 'Bug Tracker' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'Bug Tracker' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Mon Aug 01 17:44:46 EET 2022 Thread[DRDAConnThread_2,5,main] (DATABASE = Bug Tracker), (DRDAID = {3}), Database 'Bug Tracker' not found.
----------------------------------------------------------------
Mon Aug 01 17:44:49 EET 2022:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance a65c80ac-0182-5a14-7f3b-000056395d73 
on database directory G:\material kolya\level 3\summer\software engineering\project\Bug-Tracking-System\Bug Tracker System with class loader sun.misc.Launcher$AppClassLoader@266474c2 
Loaded from file:/C:/Program%20Files/Java/jdk1.8.0_162/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_162-b12
user.dir=C:\Program Files\Java\jdk1.8.0_162\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=G:\material kolya\level 3\summer\software engineering\project\Bug-Tracking-System
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Mon Aug 01 17:45:18 EET 2022: Shutting down Derby engine
